repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--overwrite-in-place", "-e", "--atomic"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.0
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--remove-duplicate-keys",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
            "-i",
            "-r",
            "-vvv",
          ]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
